### ISSUE TITLE
Notes written get removed after updating BEGIN_FSTREE

### ISSUE THREAD

**Issue by ghost** [jplindstrom/dotemacs#1]
Hello, 

I find org-fstree useful in listing all files and updating the list with C-c C-c. 
The notes which I write in this file  however get erased. 
Is this expected? 
what can I do to keep a record to which files I found useful and other notes related to the file?

Thanking you 
Anusha

**Comment by jplindstrom** [comment]
Sorry for not seeing this until now.

You found my .emacs repository where I keep my personal Emacs configuration.

This is not a repository where the Emacs module org-fstree is maintaned, and I'm not sure where you migth find one.
